name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t ${{ github.repository }} .
      - name: Deploy image
        run: |
          docker stop ${{ github.event.repository.name }} || true
          docker rm ${{ github.event.repository.name }} || true
          docker run -p 127.0.0.1:3000:3000 -d --name -e "AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}" -e "AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}" -e "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" -e "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" -e "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" -e "AUTH0_SCOPE=${{ secrets.AUTH0_SCOPE }}" ${{ github.event.repository.name }} ${{ github.repository }}
